module.exports = {
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ['hover', 'focus'],
    backgroundOpacity: ['hover', 'focus'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus'],
    borderOpacity: ['hover', 'focus'],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: ['hover', 'focus'],
    boxSizing: [],
    clear: [],
    cursor: [],
    display: [],
    divideColor: [],
    divideOpacity: [],
    divideWidth: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: ['hover', 'focus'],
    gap: [],
    gridAutoFlow: [],
    gridColumn: [],
    gridColumnEnd: [],
    gridColumnStart: [],
    gridRow: [],
    gridRowEnd: [],
    gridRowStart: [],
    gridTemplateColumns: [],
    gridTemplateRows: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: ['hover', 'focus'],
    order: [],
    outline: ['focus'],
    overflow: [],
    padding: [],
    placeholderColor: ['focus'],
    placeholderOpacity: ['focus'],
    pointerEvents: [],
    position: [],
    resize: [],
    rotate: ['hover', 'focus'],
    scale: ['hover', 'focus'],
    skew: ['hover', 'focus'],
    space: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: [],
    textColor: ['hover', 'focus'],
    textDecoration: ['hover', 'focus'],
    textOpacity: ['hover', 'focus'],
    textTransform: [],
    transform: [],
    transformOrigin: [],
    transitionDelay: [],
    transitionDuration: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    translate: ['hover', 'focus'],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
  corePlugins: {
    accessibility: false,
    alignContent: false,
    alignItems: false,
    alignSelf: false,
    appearance: false,
    backgroundAttachment: false,
    borderCollapse: false,
    borderOpacity: false,
    boxSizing: false,
    clear: false,
    container: false,
    cursor: false,
    display: false,
    divideColor: false,
    divideOpacity: false,
    divideWidth: false,
    fill: false,
    flex: false,
    flexDirection: false,
    flexGrow: false,
    flexShrink: false,
    flexWrap: false,
    float: false,
    fontSmoothing: false,
    gap: false,
    gridAutoFlow: false,
    gridColumn: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
    height: false,
    inset: false,
    justifyContent: false,
    letterSpacing: false,
    lineHeight: false,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: false,
    maxWidth: false,
    objectFit: false,
    objectPosition: false,
    opacity: false,
    order: false,
    outline: false,
    overflow: false,
    placeholderColor: false,
    placeholderOpacity: false,
    pointerEvents: false,
    position: false,
    preflight: false,
    resize: false,
    rotate: false,
    scale: false,
    skew: false,
    space: false,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textAlign: false,
    textColor: false,
    textDecoration: false,
    textOpacity: false,
    textTransform: false,
    transform: false,
    transformOrigin: false,
    transitionDelay: false,
    transitionDuration: false,
    transitionProperty: false,
    transitionTimingFunction: false,
    translate: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    width: false,
    wordBreak: false,
    zIndex: false,
  },
}
